# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from ParagraphTextEdit import ParagraphTextEdit
from RMQConnection import RabbitMQConnection


class Ui_MainWindow(object):
    def __init__(self, connection: RabbitMQConnection):
        self.connection = connection
        # __init__
    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(785, 600)
        self.mainWindow = QtWidgets.QWidget(MainWindow)
        self.mainWindow.setObjectName("mainWindow")
        
        self.title = QtWidgets.QLabel(self.mainWindow)
        self.title.setGeometry(QtCore.QRect(40, 10, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setObjectName("title")
        
        self.totalLab = QtWidgets.QLabel(self.mainWindow)
        self.totalLab.setGeometry(QtCore.QRect(130, 390, 70, 19))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.totalLab.setFont(font)
        self.totalLab.setObjectName("totalLab")
        
        self.totalInputBox = QtWidgets.QTextEdit(self.mainWindow)
        self.totalInputBox.setEnabled(False)
        self.totalInputBox.setGeometry(QtCore.QRect(250, 390, 431, 151))
        self.totalInputBox.setObjectName("totalInputBox")
        
        self.setupPanel()
        self.setupParagraphBoxes()
        
        self.ParagraphPanel.setWidget(self.PanelContent)
        MainWindow.setCentralWidget(self.mainWindow)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 785, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.connection.startConsumer()
        # setupUi
    
    def setupParagraphBoxes(self):
        self.inputBox1 = ParagraphTextEdit(self.PanelContent, self.connection, 0)
        #self.inputBox1.setFocusOutListener()
        
        self.lab1 = QtWidgets.QLabel(self.PanelContent)
        self.lab1.setGeometry(QtCore.QRect(39, 20, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lab1.setFont(font)
        self.lab1.setObjectName("lab1")
        
        self.lab2 = QtWidgets.QLabel(self.PanelContent)
        self.lab2.setGeometry(QtCore.QRect(40, 110, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lab2.setFont(font)
        self.lab2.setObjectName("lab2")
        
        self.inputBox2 = ParagraphTextEdit(self.PanelContent, self.connection, 1)

        self.lab3 = QtWidgets.QLabel(self.PanelContent)
        self.lab3.setGeometry(QtCore.QRect(40, 200, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lab3.setFont(font)
        self.lab3.setObjectName("lab3")
        
        self.inputBox3 = ParagraphTextEdit(self.PanelContent, self.connection, 2)
        # setupParagraphBoxes
    
    def setupPanel(self):
        self.ParagraphPanel = QtWidgets.QScrollArea(self.mainWindow)
        self.ParagraphPanel.setGeometry(QtCore.QRect(80, 70, 650, 301))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ParagraphPanel.sizePolicy().hasHeightForWidth())
        self.ParagraphPanel.setSizePolicy(sizePolicy)
        self.ParagraphPanel.setMaximumSize(QtCore.QSize(650, 600))
        self.ParagraphPanel.setFrameShape(QtWidgets.QFrame.Panel)
        self.ParagraphPanel.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.ParagraphPanel.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.ParagraphPanel.setWidgetResizable(False)
        self.ParagraphPanel.setObjectName("ParagraphPanel")
        
        self.PanelContent = QtWidgets.QWidget()
        self.PanelContent.setGeometry(QtCore.QRect(0, 0, 640, 299))
        self.PanelContent.setObjectName("PanelContent")
        # setupPanel
    
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "Collabora"))
        self.totalLab.setText(_translate("MainWindow", "Total"))
        self.lab1.setText(_translate("MainWindow", "Paragraph 1"))
        self.lab2.setText(_translate("MainWindow", "Paragraph 2"))
        self.lab3.setText(_translate("MainWindow", "Paragraph 3"))
        # retranslateUi

